version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bicker-pass
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
