version: '3.8'

services:
  testdb:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bicker-pass
    volumes:
      - testVolume:/var/lib/postgresql/data

volumes:
  testVolume:
    driver: local
